# Generated by Django 5.2 on 2025-04-23 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='posts',
            field=models.ManyToManyField(blank=True, related_name='pages', to='page.post'),
        ),
    ]
